version: "3.8"

services :
  database: 
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  application:
    build: ./docker/images/application
    ports:
      - "8000:80"
    depends_on:
      - database
    environment:
      - REDIS_URL=redis://cache_redis
    volumes:
      - ./docker/conf/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ./ourapp/application:/var/www/html

    
   
